### PR TITLE
overworked tests

### PR DESCRIPTION
**Pull request by wactbprot**
run the tests by:

```
npm test
```

running coverage analysis (we are at 70% by now) say:

```
npm run cover
```

HTH

### CODE REVIEW

**Comment by wactbprot** [comment]
BTW
the bad thing is that due to issue #11 all tests have to pass; it would be much better to have a failing .pop() test to demonstrate issue #15. Imho this is the weakest point of (the great) ndata. I've spend some time on this but I feel not able to solve this issue. I hope you got some time to have further look on it.

**Comment by jondubois** [comment]
Yes, it would be nice to have failing tests. I didn't even realize that pop wasn't working properly because I it was never used in SC.

**Comment by jondubois** [comment]
@wactbprot Ok, I finally managed to find some time to merge this - Thanks!
I couldn't just pull directly, so I manually cherry-picked your commits to master, see: https://github.com/TopCloud/ndata/commits/master

**Comment by wactbprot** [comment]
Great! all tests pass with v2.8.2:
```
=============================== Coverage summary ===============================
Statements   : 69.7% ( 306/439 )
Branches     : 48.4% ( 91/188 )
Functions    : 68.97% ( 40/58 )
Lines        : 69.7% ( 306/439 )
================================================================================
```

**Pull request closed without merging**
